"use client";
import { useMemo, useState } from "react";
type Play = { title: string; tag: string; people: string; time: string; color: string; icon: string; description: string; tip: string };
const plays: Play[] = [
  { title: "키링 공방", tag: "만들기", people: "1–3명", time: "20분", color: "peach", icon: "✦", description: "비즈와 참을 골라 나만의 가방 키링을 완성해요.", tip: "작은 부품은 입에 넣지 않도록 어른과 함께 확인해요." },
  { title: "딱지 배틀", tag: "승부", people: "2–4명", time: "10분", color: "blue", icon: "▰", description: "종이 한 장으로 만들고, 바닥에 톡! 누가 더 멀리 뒤집을까요?", tip: "사람을 향해 던지지 않고 평평한 바닥에서 해요." },
  { title: "보드게임 카페", tag: "전략", people: "2–6명", time: "30분", color: "yellow", icon: "♟", description: "친구들과 규칙을 정하고, 한 판만 더를 외쳐봐요.", tip: "처음 하는 친구에게 규칙을 천천히 알려주세요." },
  { title: "줄넘기 챌린지", tag: "움직이기", people: "2–8명", time: "15분", color: "mint", icon: "∿", description: "기본 뛰기부터 2단 뛰기까지, 오늘의 기록에 도전해요.", tip: "주변에 부딪힐 물건이 없는지 먼저 살펴요." },
  { title: "종이 미니어처", tag: "만들기", people: "1–2명", time: "40분", color: "lavender", icon: "⌂", description: "상상 속 방을 그리고 접어서 작은 세계를 만들어요.", tip: "가위는 자리에 앉아서 사용하고, 다 쓴 뒤 바로 정리해요." },
  { title: "몸으로 말해요", tag: "웃음", people: "4–10명", time: "15분", color: "pink", icon: "?!", description: "말 없이 몸짓만으로 제시어를 설명해요. 타이머는 60초!", tip: "친구의 몸을 잡아당기지 않고, 서로의 공간을 지켜요." },
];
const filters = ["전체", "만들기", "움직이기", "전략", "웃음", "승부"];
export default function Home() {
  const [query, setQuery] = useState(""); const [active, setActive] = useState("전체"); const [saved, setSaved] = useState<string[]>([]); const [showSaved, setShowSaved] = useState(false); const [random, setRandom] = useState<Play | null>(null);
  const visible = useMemo(() => plays.filter((play) => (active === "전체" || play.tag === active) && `${play.title} ${play.description} ${play.tag}`.toLowerCase().includes(query.toLowerCase()) && (!showSaved || saved.includes(play.title))), [active, query, saved, showSaved]);
  const toggleSave = (title: string) => setSaved((items) => items.includes(title) ? items.filter((item) => item !== title) : [...items, title]);
  return <main>
    <nav className="nav wrap" aria-label="주요 메뉴"><a className="logo" href="#top"><span>●</span> 놀자 연구소</a><div className="nav-links"><a href="#picks">오늘의 놀이</a><a href="#guide">놀이 가이드</a><button className={`save-nav ${showSaved ? "selected" : ""}`} onClick={() => setShowSaved(!showSaved)}>♡ 찜한 놀이 <b>{saved.length}</b></button></div></nav>
    <section className="hero wrap" id="top"><div className="hero-copy"><p className="eyebrow">PLAYGROUND REPORT · 2025</p><h1>오늘은 뭐 하고<br /><em>놀까?</em></h1><p className="hero-desc">친구랑 만나면 바로 시작할 수 있는<br />요즘 놀이를 한곳에 모았어요.</p><a href="#picks" className="primary-btn">놀이 둘러보기 <span>↘</span></a></div><div className="hero-art" aria-label="친구들과 즐겁게 노는 모습을 표현한 일러스트"><div className="sun">✳</div><div className="blob blob-one"></div><div className="blob blob-two"></div><div className="doodle doodle-star">✦</div><div className="doodle doodle-heart">♡</div><div className="sticker">LET’S<br /><strong>PLAY!</strong></div><div className="mini-card">이번 주<br /><b>인기 놀이</b><span>↗</span></div></div></section>
    <section className="content wrap" id="picks"><div className="section-heading"><div><p className="eyebrow">FIND YOUR PLAY</p><h2>지금 끌리는 놀이를<br /><span>찾아봐요</span></h2></div><button className="random-btn" onClick={() => setRandom(plays[Math.floor(Math.random() * plays.length)])}>✦ 뭐 하지? 랜덤 추천</button></div><div className="toolbar"><label className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="놀이 이름이나 키워드를 검색해 보세요" aria-label="놀이 검색" /></label><div className="filters" role="tablist" aria-label="놀이 종류 필터">{filters.map((filter) => <button key={filter} className={active === filter ? "active" : ""} onClick={() => setActive(filter)}>{filter}</button>)}</div></div><div className="play-grid">{visible.map((play, index) => <article className={`play-card ${play.color}`} key={play.title}><div className="card-top"><span className="number">0{index + 1}</span><button className={`heart ${saved.includes(play.title) ? "hearted" : ""}`} onClick={() => toggleSave(play.title)} aria-label={`${play.title} ${saved.includes(play.title) ? "찜 취소" : "찜하기"}`}>{saved.includes(play.title) ? "♥" : "♡"}</button></div><div className="play-icon">{play.icon}</div><div className="card-copy"><span className="tag">{play.tag}</span><h3>{play.title}</h3><p>{play.description}</p></div><div className="meta"><span>♧ {play.people}</span><span>◷ {play.time}</span></div><div className="tip">TIP <span>{play.tip}</span></div></article>)}</div>{visible.length === 0 && <div className="empty">아직 찜한 놀이가 없어요. 마음에 드는 카드의 ♡를 눌러보세요!</div>}</section>
    <section className="guide" id="guide"><div className="wrap guide-inner"><div><p className="eyebrow">PLAY NICE, PLAY SAFE</p><h2>잘 노는 것도<br /><em>멋진 실력</em>이에요.</h2></div><div className="guide-list"><div><b>01</b><span>친구가 싫다고 하면<br />바로 멈춰요.</span></div><div><b>02</b><span>차례와 규칙은<br />함께 정해요.</span></div><div><b>03</b><span>끝나면 함께<br />정리해요.</span></div></div></div></section>
    <footer className="footer wrap"><span>놀자 연구소</span><span>매일 새롭게, 함께 즐겁게.</span><span>© 2025 PLAY LAB</span></footer>
    {random && <div className="modal-backdrop" onClick={() => setRandom(null)}><div className={`random-modal ${random.color}`} onClick={(e) => e.stopPropagation()}><button className="close" onClick={() => setRandom(null)} aria-label="닫기">×</button><p className="eyebrow">TODAY’S PICK</p><div className="modal-icon">{random.icon}</div><h2>오늘은<br /><em>{random.title}</em> 어때요?</h2><p>{random.description}</p><button className="primary-btn" onClick={() => setRandom(null)}>좋아, 해볼래!</button></div></div>}
  </main>;
}
